
import Foundation

struct VideoMetadata {
    var title: String
    var channel: String
    var date: String
    var url: String
}

class AIContentService {
    static let shared = AIContentService()
    
    enum AIError: Error {
        case missingKey
        case invalidResponse
        case apiError(String)
    }
    
    func generateArticle(transcript: String, metadata: VideoMetadata, apiKey: String, completion: @escaping (Result<Article, Error>) -> Void) {
        guard !apiKey.isEmpty else {
            completion(.failure(AIError.missingKey))
            return
        }
        
        let prompt = """
        You are an expert tech journalist. Write a detailed, authoritative blog post based on the following YouTube video transcript.
        
        Video Title: \(metadata.title)
        Channel: \(metadata.channel)
        Date: \(metadata.date)
        Original URL: \(metadata.url)
        
        Instructions:
        1. Write a catchy, SEO-optimized Title.
        2. Write a detailed, structured blog post (HTML format: use <h3>, <p>, <ul>, <table>).
        3. Do NOT output a full HTML document (no <html> or <body> tags), just the content.
        4. Reference the YouTuber ("According to [Channel]...") as the authoritative source on new findings.
        5. Verify facts from the transcript. If the transcript mentions "Soldered" vs "Modular", highlight that.
        6. Summary: Provide a 2 sentence SEO meta description at the very end, separated by "||SUMMARY||".
        
        Transcript:
        \(transcript.prefix(15000)) 
        """
        // Truncate to avoid context limit if huge
        
        // Mocking Request for MVP? No, let's try real request structure.
        let url = URL(string: "https://api.openai.com/v1/chat/completions")!
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.addValue("Bearer \(apiKey)", forHTTPHeaderField: "Authorization")
        request.addValue("application/json", forHTTPHeaderField: "Content-Type")
        
        let body: [String: Any] = [
            "model": "gpt-4o", // or gpt-3.5-turbo
            "messages": [
                ["role": "system", "content": "You are a helpful expert coding assistant."],
                ["role": "user", "content": prompt]
            ],
            "temperature": 0.7
        ]
        
        request.httpBody = try? JSONSerialization.data(withJSONObject: body)
        
        URLSession.shared.dataTask(with: request) { data, response, error in
            if let error = error {
                completion(.failure(error))
                return
            }
            
            guard let data = data else {
                completion(.failure(AIError.invalidResponse))
                return
            }
            
            // Parse OpenAI Response
            // MVP: Assuming success for simplicity in error handling
            do {
                if let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
                   let choices = json["choices"] as? [[String: Any]],
                   let first = choices.first,
                   let message = first["message"] as? [String: Any],
                   let content = message["content"] as? String {
                    
                    // Parse Content (Title? Body? Summary?)
                    // We asked for HTML. But the LLM might wrap in markdown ```html code```
                    var cleanContent = content.replacingOccurrences(of: "```html", with: "").replacingOccurrences(of: "```", with: "")
                    
                    // Split Summary
                    var summary = "Generated by AI"
                    if let range = cleanContent.range(of: "||SUMMARY||") {
                        summary = String(cleanContent[range.upperBound...]).trimmingCharacters(in: .whitespacesAndNewlines)
                        cleanContent = String(cleanContent[..<range.lowerBound])
                    }
                    
                    // Extract Title (heuristic: first line?)
                    var title = metadata.title
                    let lines = cleanContent.components(separatedBy: "\n").filter { !$0.isEmpty }
                    if let firstLine = lines.first, firstLine.lowercased().hasPrefix("title:") {
                        title = firstLine.replacingOccurrences(of: "Title:", with: "").trimmingCharacters(in: .whitespaces)
                        // Remove title line from content
                         if let range = cleanContent.range(of: firstLine) {
                            cleanContent.removeSubrange(range)
                        }
                    }
                    
                    let article = Article(
                        title: title,
                        slug: metadata.title.lowercased().replacingOccurrences(of: " ", with: "-").filter { "abcdefghijklmnopqrstuvwxyz0123456789-".contains($0) },
                        summary: summary,
                        contentHTML: cleanContent,
                        author: "AI (Source: \(metadata.channel))"
                    )
                    
                    completion(.success(article))
                    
                } else {
                    completion(.failure(AIError.apiError("Failed to parse JSON")))
                }
            } catch {
                completion(.failure(error))
            }
        }.resume()
    }
}
