
import Foundation

struct VideoMetadata {
    var title: String
    var channel: String
    var date: String
    var url: String
}

struct PolishedResult: Decodable {
    let html: String
    let seo_score: Int
    let keywords: [String]
    let analysis: String
}

class AIContentService {
    static let shared = AIContentService()
    
    enum AIError: Error {
        case missingKey
        case invalidResponse
        case apiError(String)
    }
    
    // Test Connection
    func testConnection(provider: String, apiKey: String, model: String, endpointURL: String = "", completion: @escaping (Result<String, Error>) -> Void) {
        let prompt = "Say 'OK' if you can hear me."
        // We reuse generateArticle logic but with short prompt and raw output
        // For simplicity, we create a specialized request
        
        generateRaw(prompt: prompt, system: "You are a test bot.", provider: provider, apiKey: apiKey, model: model, endpointURL: endpointURL) { result in
             switch result {
             case .success(let content):
                 completion(.success(content))
             case .failure(let error):
                 completion(.failure(error))
             }
        }
    }
    
    func generateArticle(transcript: String, metadata: VideoMetadata, apiKey: String, provider: String = "OpenAI", model: String = "gpt-4o", endpointURL: String = "", completion: @escaping (Result<Article, Error>) -> Void) {
        
        let systemPrompt = "You are an expert tech journalist. Output raw HTML content (no ```html wrappers)."
        let userPrompt = """
        Write a detailed, authoritative blog post based on this YouTube transcript.
        
        Title: \(metadata.title)
        Channel: \(metadata.channel)
        
        Instructions:
        1. Write a catchy Title.
        2. Body must be HTML (<h3>, <p>, <ul>). No <html> tags.
        3. Reference the YouTuber.
        4. End with "||SUMMARY||" followed by a 2-sentence meta description.
        
        Transcript:
        \(transcript.prefix(25000))
        """
        
        generateRaw(prompt: userPrompt, system: systemPrompt, provider: provider, apiKey: apiKey, model: model, endpointURL: endpointURL) { result in
            switch result {
            case .success(let content):
                 // Parse
                 var clean = content.replacingOccurrences(of: "```html", with: "").replacingOccurrences(of: "```", with: "")
                 
                 var summary = "Generated by AI"
                 if let range = clean.range(of: "||SUMMARY||") {
                     summary = String(clean[range.upperBound...]).trimmingCharacters(in: .whitespacesAndNewlines)
                     clean = String(clean[..<range.lowerBound])
                 }
                 
                 // Heuristic Title extraction if in text
                 var title = metadata.title
                 let lines = clean.components(separatedBy: "\n").filter { !$0.isEmpty }
                 if let first = lines.first, first.lowercased().hasPrefix("title:") {
                     title = first.replacingOccurrences(of: "Title:", with: "").trimmingCharacters(in: .whitespaces)
                     clean = clean.replacingOccurrences(of: first, with: "")
                 }
                 
                 let article = Article(
                     title: title,
                     slug: metadata.title.lowercased().filter { "abcdefghijklmnopqrstuvwxyz0123456789".contains($0) } + "-" + String(Int(Date().timeIntervalSince1970)),
                     summary: summary,
                     contentHTML: clean,
                     author: "AI"
                 )
                 completion(.success(article))
                 
            case .failure(let error):
                completion(.failure(error))
            }
        }
    func polishArticle(contentHTML: String, apiKey: String, provider: String = "OpenAI", model: String = "gpt-4o", endpointURL: String = "", completion: @escaping (Result<PolishedResult, Error>) -> Void) {
        
        let systemPrompt = "You are an elite SEO & AI Optimization Expert. Output valid JSON only."
        
        let userPrompt = """
        Optimize and polish the following blog post. Return a JSON object with this structure:
        {
          "html": "The refined clean HTML body content (no <html> tags)",
          "seo_score": 85, // 0-100 score based on optimization quality
          "keywords": ["keyword1", "keyword2"], // 5-10 potential heavy-hitter keywords
          "analysis": "Short explanation of what was improved and why."
        }

        Instructions for 'html':
        1. **Strip Chatter**: Remove "Here is the article", "Sources", etc.
        2. **Semantic**: Use H2/H3.
        3. **Snippets**: Bold direct answers.
        4. **Visuals**: Use <img src="https://placehold.co/600x400?text=Scan+Mac" alt="Scan Mac" />
        
        Content:
        \(contentHTML.prefix(25000))
        """
        
        generateRaw(prompt: userPrompt, system: systemPrompt, provider: provider, apiKey: apiKey, model: model, endpointURL: endpointURL) { result in
             switch result {
             case .success(let content):
                  // Try to find JSON block
                  var jsonString = content
                  if let start = content.range(of: "{"), let end = content.range(of: "}", options: .backwards) {
                       jsonString = String(content[start.lowerBound...end.upperBound])
                  }
                  
                  if let data = jsonString.data(using: .utf8),
                     let result = try? JSONDecoder().decode(PolishedResult.self, from: data) {
                       completion(.success(result))
                  } else {
                       completion(.failure(AIError.apiError("Failed to parse JSON response")))
                  }
             case .failure(let error):
                  completion(.failure(error))
             }
        }
    }
    
    // Unified Backend
    private func generateRaw(prompt: String, system: String, provider: String, apiKey: String, model: String, endpointURL: String, completion: @escaping (Result<String, Error>) -> Void) {
        
        if provider == "Anthropic" {
            generateAnthropic(prompt: prompt, system: system, apiKey: apiKey, model: model, completion: completion)
            return
        }
        
        // OpenAI / OpenRouter / Ollama (OpenAI Compatible)
        var baseURL = ""
        var headers: [String: String] = [
            "Content-Type": "application/json",
            "Authorization": "Bearer \(apiKey)"
        ]
        
        switch provider {
        case "OpenAI":
            baseURL = "https://api.openai.com/v1/chat/completions"
        case "OpenRouter":
            baseURL = "https://openrouter.ai/api/v1/chat/completions"
            headers["HTTP-Referer"] = "https://webmakr.app"
            headers["X-Title"] = "WebMakr"
        case "Ollama":
            // Use provided URL or default
            let base = endpointURL.isEmpty ? "http://localhost:11434" : endpointURL
            // Ensure /v1/chat/completions attached
            if base.hasSuffix("/v1/chat/completions") {
                baseURL = base
            } else if base.hasSuffix("/") {
                 baseURL = base + "v1/chat/completions"
            } else {
                 baseURL = base + "/v1/chat/completions"
            }
            headers["Authorization"] = "Bearer ollama" // Not always needed but innocuous
        default:
             baseURL = "https://api.openai.com/v1/chat/completions"
        }
        
        guard let url = URL(string: baseURL) else { return }
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        for (k, v) in headers { request.addValue(v, forHTTPHeaderField: k) }
        
        let body: [String: Any] = [
            "model": model,
            "messages": [
                ["role": "system", "content": system],
                ["role": "user", "content": prompt]
            ],
            "temperature": 0.7
        ]
        request.httpBody = try? JSONSerialization.data(withJSONObject: body)
        
        URLSession.shared.dataTask(with: request) { data, _, error in
            if let error = error { completion(.failure(error)); return }
            guard let data = data else { completion(.failure(AIError.invalidResponse)); return }
            
            // Print raw for debug
             if let str = String(data: data, encoding: .utf8) { print("Raw API: \(str)") }
            
            do {
                if let json = try JSONSerialization.jsonObject(with: data) as? [String: Any] {
                     // Check Error
                     if let errorObj = json["error"] as? [String: Any], let msg = errorObj["message"] as? String {
                         completion(.failure(AIError.apiError(msg)))
                         return
                     }
                     if let msg = json["error"] as? String { // Ollama simple error
                          completion(.failure(AIError.apiError(msg)))
                          return
                     }
                    
                     if let choices = json["choices"] as? [[String: Any]],
                        let first = choices.first,
                        let message = first["message"] as? [String: Any],
                        let content = message["content"] as? String {
                         completion(.success(content))
                     } else {
                         completion(.failure(AIError.apiError("No content in response")))
                     }
                }
            } catch {
                completion(.failure(error))
            }
        }.resume()
    }
    
    private func generateAnthropic(prompt: String, system: String, apiKey: String, model: String, completion: @escaping (Result<String, Error>) -> Void) {
        let url = URL(string: "https://api.anthropic.com/v1/messages")!
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.addValue(apiKey, forHTTPHeaderField: "x-api-key")
        request.addValue("2023-06-01", forHTTPHeaderField: "anthropic-version")
        request.addValue("application/json", forHTTPHeaderField: "content-type")
        
        let body: [String: Any] = [
            "model": model,
            "max_tokens": 4096,
            "system": system,
            "messages": [
                ["role": "user", "content": prompt]
            ]
        ]
        request.httpBody = try? JSONSerialization.data(withJSONObject: body)
        
        URLSession.shared.dataTask(with: request) { data, _, error in
            if let error = error { completion(.failure(error)); return }
            guard let data = data else { completion(.failure(AIError.invalidResponse)); return }
            
            do {
                if let json = try JSONSerialization.jsonObject(with: data) as? [String: Any] {
                    if let type = json["type"] as? String, type == "error" {
                        if let errObj = json["error"] as? [String: Any], let msg = errObj["message"] as? String {
                            completion(.failure(AIError.apiError(msg)))
                            return
                        }
                    }
                    
                    if let contentArr = json["content"] as? [[String: Any]],
                       let first = contentArr.first,
                       let text = first["text"] as? String {
                        completion(.success(text))
                    } else {
                        completion(.failure(AIError.apiError("Invalid Anthropic Response")))
                    }
                }
            } catch {
                completion(.failure(error))
            }
        }.resume()
    }
}
